### ISSUE TITLE
Build failure with nghttp2 v1.0.0: use of undeclared identifier 'NGHTTP2_CLIENT_CONNECTION_PREFACE'

### ISSUE THREAD

**Issue by ryandesign** [bagder/curl#273]
curl v7.42.1 cannot be compiled with nghttp2 v1.0.0:

```
http2.c:1022:6: error: use of undeclared identifier 'NGHTTP2_CLIENT_CONNECTION_PREFACE'
     NGHTTP2_CLIENT_CONNECTION_PREFACE,
     ^
http2.c:1023:6: error: use of undeclared identifier 'NGHTTP2_CLIENT_CONNECTION_PREFACE_LEN'
     NGHTTP2_CLIENT_CONNECTION_PREFACE_LEN,
     ^
```

Compiles fine with nghttp2 v0.7.14. The nghttp2 API was changed in a backward-incompatible way in version 1.0.0, described here: https://nghttp2.org/documentation/package_README.html#migration-from-v0-7-15-or-earlier

**Comment by bagder** [comment]
Thanks.

We have merged the 1.0.0 compatible fixes into the http2-multiplex branch that will soon be merged into master and thus this is planned to work fine in the next release. For 7.42.1 or later I recommend sticking to 0.7.15 or earlier.

**Comment by centminmod** [comment]
ah glad i found this bug as it broke my docker image which bundles nghttp and curl 7.42.1 on rebuild !
