### ISSUE TITLE
<windows.h> not found on Windows 10 with Visual Studio 2015

### ISSUE THREAD

**Issue by bkircher** [bagder/curl#454]
Compiling current master with winbuild/ fails for me on Windows 10 with Visual Studio 2014:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23026 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>cd \Users\bkircher\src\curl\winbuild

C:\Users\bkircher\src\curl\winbuild>nmake /f Makefile.vc mode=dll MACHINE=x64

Microsoft (R) Program Maintenance Utility Version 14.00.23026.0
Copyright (C) Microsoft Corporation.  All rights reserved.

configuration name: libcurl-vc-x64-release-dll-ipv6-sspi-winssl

Generating prerequisite files
* C:\Users\bkircher\src\curl\Makefile
* C:\Users\bkircher\src\curl\src\tool_hugehelp.c
* C:\Users\bkircher\src\curl\include\curl\curlbuild.h

Warning: The curl manual could not be integrated in the source. This means when
you build curl the manual will not be available (curl --man). Integration of
the manual is not required and a summary of the options will still be available
(curl --help). To integrate the manual your PATH is required to have
groff/nroff, perl and optionally gzip for compression.
Could Not Find C:\Users\bkircher\src\curl\winbuild\LIBCURL_OBJS.inc
Could Not Find C:\Users\bkircher\src\curl\winbuild\CURL_OBJS.inc
        cl.exe /O2 /DNDEBUG /MD /I. /I ../lib /I../include /nologo /W3 /EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL /I"../../deps/include"  /DUSE_WIN32_IDN /DWANT_IDN_PROTOTYPES  /DUSE_IPV6  /DUSE_WINDOWS_SSPI /DUSE_SCHANNEL /Fo"..\builds\libcurl-vc-x64-release-dll-ipv6-sspi-winssl-obj-lib/file.obj"  ..\lib\file.c
file.c
c:\users\bkircher\src\curl\lib\curl_setup.h(248): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
```

Build on Windows 8.1 and Visual Studio 2012 works as expected.

Current master:
```
$ git log --oneline | head -n1
684bf30 RELEASE-NOTES: synced with 6b56901b56e
```

Windows.h is installed with WDK:
```
C:\Users\bkircher\src\curl\winbuild>where windows.h
INFO: Could not find files for the given pattern(s).

C:\Users\bkircher\src\curl\winbuild>ffind /L /S windows.h
C:\Program Files (x86)\Windows Kits\8.1\Include\um\Windows.h
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um\Windows.h
```

**Comment by jay** [comment]
I don't have a setup like that yet but if nobody else takes this I'll give it a shot. Are you using an RC build of VS2015 or release, and are you using that version's Visual Studio command prompt? What are the values of environment variables INCLUDE, LIB, LIBPATH?

**Comment by bkircher** [comment]
> Are you using an RC build of VS2015 or release

A released version of Visual Studio Community

> are you using that version's Visual Studio command prompt?

I'm using the VS2015 x64 Native Tools Command Prompt. Basically:
`cmd.exe /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"" amd64`

> What are the values of environment variables INCLUDE, LIB, LIBPATH?

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>set INCLUDE
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\wdf\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um;C:\Program Files (x86)\Windows Kits\10\include\wdf\shared;C:\Program Files (x86)\Windows Kits\10\include\wdf\um;C:\Program Files (x86)\Windows Kits\10\include\wdf\winrt;

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>set LIB
LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\wdf\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\wdf\um\x64;
LIBPATH=C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References;C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\1.0.0.0;C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0;C:\Program Files (x86)\Windows Kits\10\References\indows.Networking.Connectivity.WwanContract\1.0.0.0;C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>set LIBPATH
LIBPATH=C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References;C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\1.0.0.0;C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0;C:\Program Files (x86)\Windows Kits\10\References\indows.Networking.Connectivity.WwanContract\1.0.0.0;C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;
```

**Comment by captain-caveman2k** [comment]
I'm pretty sure I've compiled winbuild against VS2015 so can take a look at this.

Just out of interest have you tried the x86 or cross compiler command line?

**Comment by bkircher** [comment]
> Just out of interest have you tried the x86 or cross compiler command line?

Of course not! :-)
I'll give it a shot tomorrow.

**Comment by bkircher** [comment]
Same thing with x86 command line.

**Comment by bkircher** [comment]
Following include paths are set in a standard Visual Studio 2015 project that targets Windows 8.1:

![includedirs](https://cloud.githubusercontent.com/assets/536464/10162128/46219bb0-66a9-11e5-9f47-da9236ebbb95.png)

**Comment by captain-caveman2k** [comment]
Hi Ben,

Cheers for the extra information and for trying x86. I will try this myself - hopefully tomorrow but if not the weekend.

Kind regards

Steve

**Comment by bkircher** [comment]
Got it.

http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx

Excerpt from the above:

"The headers, sources, and libraries are now distributed as part of a separate
Universal CRT SDK. This SDK is included with Visual Studio; it is installed by
default to C:\Program Files (x86)\Windows Kits\10."

**Comment by bkircher** [comment]
Okay, it's a Windows issue:
[UniversalCRT detection breaks when Windows Driver Kit is installed](https://connect.microsoft.com/VisualStudio/feedback/details/1610302/universalcrt-detection-breaks-when-windows-driver-kit-is-installed)

Corresponding Stackoverflow Question that might be of help:
[Unable to compile and link simple C++ program with Visual Studio 2015 command line tools](http://stackoverflow.com/questions/32885229/unable-to-compile-and-link-simple-c-program-with-visual-studio-2015-command-li)

**Comment by bkircher** [comment]
Thanks for all the support.
