### ISSUE TITLE
cyassl and wolfssl builds are broken

### ISSUE THREAD

**Issue by bagder** [bagder/curl#566]
I tried to build with cyassl 3.3.2, wolfssl 3.4.4 and wolfssl 3.7.0. curl failed to build with all of them.

The 3.7.0 is the latest wolfssl release and the curl build stopped at this (I fixed a compiler warning first that I'll push separately):

~~~~
$ make -s
Making all in lib
Making all in src
  CCLD     curl
../lib/.libs/libcurl.a(libcurl_la-cyassl.o): In function `cyassl_connect_step1':
/home/daniel/src/curl/lib/vtls/cyassl.c:146: undefined reference to `wolfSSLv3_client_method'
../lib/.libs/libcurl.a(libcurl_la-cyassl.o): In function `cyassl_connect_step2':
/home/daniel/src/curl/lib/vtls/cyassl.c:416: undefined reference to `wolfSSL_get_peer_certificate'
/home/daniel/src/curl/lib/vtls/cyassl.c:422: undefined reference to `wolfSSL_X509_get_der'
collect2: error: ld returned 1 exit status
Makefile:774: recipe for target 'curl' failed
make[2]: *** [curl] Error 1
Makefile:653: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:878: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by bagder** [comment]
ping @gnawhleinad. @jay and @moparisthebest. How did you build this the last times you modified curl for cyassl/wolfssl? I just don't understand why nothing works for me?

**Comment by jay** [comment]
I'm guessing this is probably you are missing some legacy OpenSSL emulation or something. wolfSSL and cyassl we're using OpenSSL emulation in some places I recall. Also wolfSSL by default builds in a minimum configuration so that might be something.

I haven't used wolfSSL in a while. I have 3.6.3 that's runs on curl master afcab2c 2015-12-14 without a problem:

~~~
curl 7.47.0-DEV (i386-pc-win32) libcurl/7.47.0-DEV wolfSSL/3.6.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp
smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug Largefile NTLM SSL
~~~

I built wolfSSL using our Windows build script [projects/build-wolfssl.bat](https://github.com/bagder/curl/blob/curl-7_46_0/projects/build-wolfssl.bat) which builds it for maximum compatibility. I had to make a few changes so that wolfSSL would build in a way that was compatible with most websites because they shut off some hash functions and stuff. You can see what I did in [projects/wolfssl_options.h](https://github.com/bagder/curl/blob/curl-7_46_0/projects/wolfssl_options.h#L1-L40). I'll guess you're probably missing `--enable-opensslextra` or something.

I just checked out and built [v3.7.3](https://github.com/wolfSSL/wolfssl/tree/v3.7.3) but I get one error, `wolfSSLv3_client_method` is no longer present. They probably no longer enable SSLv3 during the build. So we'll have to do something like a compile-time check if it's enabled.

**Comment by dfandrich** [comment]
My autobuilds are currently using WolfSSL 3.4.6 without issue. I'm also
guessing that --enable-opensslextra may be what you're missing. I used these
options to configure it:
--enable-ecc --enable-crl --enable-sni --enable-aesgcm --enable-dsa --disable-arc4 --enable-opensslextra

**Comment by bagder** [comment]
Thanks both of you. With @dfandrich's trick it links with everything except the SSLv3 function and if I rebuild wolfssl with `--enable-sslv3` that works too.

**Comment by bagder** [comment]
In commit 1ff3a07be9 it should now handle wolfssl builds without SSLv3
